modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="See Curseforge for details"

[[mods]] #mandatory
    modId="techcraft" #mandatory
    version="1.17.1-0.1.8" #mandatory
    displayName="Techcraft" #mandatory
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/tc-techcraft"
    #logoFile="logo.png" #optional
    #credits="Thanks for this example mod goes to Java" #optional
    authors="tech0006" #optional
    description='''A lot of tech, computers, mechanics and more...'''

[[dependencies.techcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.techcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.techcraft]]
    modId = "jei"
    mandatory = false
    versionRange = "[8,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.techcraft]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3,)"
    ordering = "NONE"
    side = "BOTH"
