modLoader = "javafml"
loaderVersion = "[36,)"
license="See Curseforge for details"

[[mods]]
    modId = "techcraft"
    version = "1.16.5-0.1.8"
    displayName = "Techcraft"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/tc-techcraft"
    logoFile="TechcarftLogo.png" #optional
    authors = "tech0006"
    description = '''A lot of tech, computers, mechanics and more...'''

[[dependencies.techcraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.techcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.techcraft]]
    modId = "jei"
    mandatory = false
    versionRange = "[6,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.techcraft]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3,)"
    ordering = "NONE"
    side = "BOTH"
