modLoader = "javafml"
loaderVersion = "[31,)"

[[mods]]
    modId = "techcraft"
    version = "1.15.2-0.0.7"
    displayName = "Techcraft"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/tc-techcraft"
    authors = "tech0006"
    description = '''A lot of tech, computers, mechanics and more...'''

[[dependencies.techcraft]]
    modId = "forge"
    mandatory = true
    versionRange = "[31,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.techcraft]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.15.2]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.techcraft]]
    modId = "jei"
    mandatory = false
    versionRange = "[6,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.techcraft]]
    modId = "waila"
    mandatory = false
    versionRange = "[1,)"
    ordering = "NONE"
    side = "BOTH"
